git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
gui:
  showIcons: true
  showBottomLine: false
  border: hidden
  theme:
    lightTheme: false
    activeBorderColor:
      - "#a6e3a1" # Green
      - bold
    inactiveBorderColor:
      - "#cdd6f4" # Text
    optionsTextColor:
      - "#89b4fa" # Blue
    selectedLineBgColor:
      - "#313244" # Surface0
    selectedRangeBgColor:
      - "#313244" # Surface0
    cherryPickedCommitBgColor:
      - "#94e2d5" # Teal
    cherryPickedCommitFgColor:
      - "#89b4fa" # Blue
    unstagedChangesColor:
      - red # Red
customCommands:
  - key: "<c-r>" # Control + R
    prompts:
    - type: "input"
      title: "Commit message"
      initialValue: "{{.SelectedLocalCommit.Name}}"
    command: "git commit --amend -S -m '{{index .PromptResponses 0}}'"
    context: "global"
