env:
  TERM: xterm-256color

window:
  padding:
    x: 16
    y: 16
  startup_mode: Maximized
  decorations_theme_variant: Dark
  decorations: buttonless
  option_as_alt: OnlyLeft

scrolling:
  history: 10000
  multiplier: 2
    
font:
  size: 15.0
  normal:
    family: Mononoki Nerd Font Mono
    style: Regular
  bold:
    family: Mononoki Nerd Font Mono
    style: Bold
  italic:
    family: Mononoki Nerd Font Mono
    style: Bold
  bold_italic:
    family: Mononoki Nerd Font Mono
    style: Bold Italic

bell:
  duration: 10
  animation: EaseOutExpo

colors:
  primary:
    background: '0x0d1117'
    foreground: '0xb3b1ad'

  normal:
    black:   '0x484f58'
    red:     '0xff7b72'
    green:   '0x3fb950'
    yellow:  '0xd29922'
    blue:    '0x58a6ff'
    magenta: '0xbc8cff'
    cyan:    '0x39c5cf'
    white:   '0xb1bac4'

  bright:
    black:   '0x6e7681'
    red:     '0xffa198'
    green:   '0x56d364'
    yellow:  '0xe3b341'
    blue:    '0x79c0ff'
    magenta: '0xd2a8ff'
    cyan:    '0x56d4dd'
    white:   '0xf0f6fc'

  indexed_colors:
    - { index: 16, color: '0xd18616' }
    - { index: 17, color: '0xffa198' }

cursor:
  style:
    shape: Block
    blinking: On
  blink_interval: 500
  unfocused_hollow: true

shell:
  program: /opt/homebrew/bin/zsh
  args:
    - --login

key_bindings:
  - { key: V, mods: Command, action: Paste }
  - { key: C, mods: Command, action: Copy }
  - { key: F, mods: Command, action: SearchForward }
  - { key: F, mods: Command|Shift, action: SearchBackward }

    # Command + , for preferences on macOS
  - key: Comma
    mods: Command
    command:
      program: tmux
      args:
        - popup
        - -E
        - -w 50%
        - -h 50%
        - nvim ~/.config/alacritty/alacritty.yml
