# This is a snippet file, dark_listener.swift uses it to generate a sourceable color scheme.
# Refer to launchd/dark_listener.swift for more information about what this does
schemes:
  github_light: &github_light
    primary:
      background: '0xffffff'
      foreground: '0x0E1116'

    normal:
      black:   '0x24292f'
      red:     '0xcf222e'
      green:   '0x116329'
      yellow:  '0x4d2d00'
      blue:    '0x0969da'
      magenta: '0x8250df'
      cyan:    '0x1b7c83'
      white:   '0x6e7781'

    bright:
      black:   '0x57606a'
      red:     '0xa40e26'
      green:   '0x1a7f37'
      yellow:  '0x633c01'
      blue:    '0x218bff'
      magenta: '0xa475f9'
      cyan:    '0x3192aa'
      white:   '0x8c959f'

    indexed_colors:
      - { index: 16, color: '0xd18616' }
      - { index: 17, color: '0xa40e26' }

  github_dark: &github_dark
    primary:
      background: '0x0d1117'
      foreground: '0xb3b1ad'

    normal:
      black:   '0x484f58'
      red:     '0xff7b72'
      green:   '0x3fb950'
      yellow:  '0xd29922'
      blue:    '0x58a6ff'
      magenta: '0xbc8cff'
      cyan:    '0x39c5cf'
      white:   '0xb1bac4'

    bright:
      black:   '0x6e7681'
      red:     '0xffa198'
      green:   '0x56d364'
      yellow:  '0xe3b341'
      blue:    '0x79c0ff'
      magenta: '0xd2a8ff'
      cyan:    '0x56d4dd'
      white:   '0xf0f6fc'

    indexed_colors:
      - { index: 16, color: '0xd18616' }
      - { index: 17, color: '0xffa198' }

colors: *github_<replace>
